sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

after_success:
  - mvn jacoco:report coveralls:report

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "sZ2cWwEeCHZwQh32v2sVi4H0XHE9uvzxcEujgerQSCzxfNJfy54L4zVH0scvITOum/gf3EWcPocWJ8C46ixuHC10cDsYlYfvXVWwlJVxXEUuPouvcSifqpSIfGDyQWf1VBap18UuQzjA5TsZgg6dZyQiRmHWouim9eiUXiJCNu2KIAN0fSB6E6Hck6fbttwhX2EjySMjWCesIuo3eGuMnu1MqH//4qw8OyoQg/YX+rkfBrDh358qpUF7e37oFfa7U5sXJy3Nh3WsqQPB2j24o8Nk6XIz1TMaAdo9z+n7hDnFOCrh5Mhwxr4ki27+s5ujL9tmZFiewHn0uXXMNCsmvwatFbquCrvcjSdH29aPzdhroxMEC4e416qN9antu97MMY6pBA3VoPSmRcxLr4kMfciA0cUIy5NBcO5zRE66/h4pjX2nban1GTBzFpkH4ciwnmOrjuy0iQYRzrNJT5pvKYnJcF9ELqFmzKbUVldfRDsqQApOnRKA4/FzJKWGNIYO2GCnAZfkIGWZjy3L2haqYiy6EXfMhc0AUl2qZxpNQP5H8ZFuz7VCxPiOlikhiUApegwS6Kw1QVvj4D7+jlyYJdxKWQSZ/1MIMvTKRRpOwm56Pxqe9XFnJYIq5a8aytNdYpYgeKDWHgLyYUhnrB6LWf/AuzGEdSSm6/zjaVlNRgA="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "AWY11NmkKwvRSB3qt6xr4X/mcR5Kfr6FsEPMg6au/EvkZXmBaR/hQ1bFNgqxzM/D4SFNEbkMO1YSMianoQZThhMqI88NVVSiN0uDUvi6pUExN9c81MFFJzYiyVeFqafUQ8zxV4bQ/mL9CE7v4Sww8SANmSkBuY7QLdf21J+RACfPLjzxxJqHILWldXH6yW96Qk/nmxdp3+fkVyUzv5ub7NdBpGgYjsUJ39GRSXkU4310FFwRbSnOrquP6NNpR4M5bDuUmoWj+BXCvDUdgE17cy12evk8xH+4VfLq9Q3IyXnJbzicen1by5lWbqEGpZCz0oXVIF8GMDmodVYzrDOuVwAvIX9Y05lqVf2FYJO0S0vk9fFUC0MHdoaNnVlzrEQF3GPiZJYPmNhXMB8ScL11Db6sT7+rs9lMshTmSlHhw+8A/L2iya6JFAA0X4044dIxZJvL18aasBvef2k0ryJrSz+4yQK4OdwUjdIfl6IluECbTboi65F8ZIMCHAi6ytRgmh4AFWPKC3K7VuSb75x7+1QOGRa09lpln30y9bw5pd0c1kjuEaaVsI4ZQv8Lf44R82hHniilbFTH9UYX9ZNjXSHPjzPNZTQqSZvtRDmAjNGKhe37f2Gt3jN29XyeNjilcWc8okbdXo+V7GdjXgXb3lWOLZKFagrBPRNd2KTng0A="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "ZKqorsi6weSsMycKGB1hb55EOBGmM0QlngUDcFuBiR0P44DT0JPN0TUYL4/w1wzJa459fX34KdGtHEC90FY5kyH6Fty2yo7zV62MmFCLZ3s/0SlNtwATrXHYXNxrMOwZ/+UXJVkn67KUi1s7wv0Rhq+XHHP2WbF1KIqZtrV8K2NNYodUn3ERza/+1UCoFOs7yao8IfbZGXOVCrtSTvxYjrI50sJdt6he0UqJjq46NJCjF8q2A6UTtpXELlswJL54Df/+6uLsb94NrReTUjEKBFpl7/kjgca67fVsnrtjvJ/mWWNiN9DAF7MYkooWLw3BfU3EBo7s4K33JmyjPwi99X69CDy+E1uW4tPHJxC9HVajLNzjDICrUOYBL42ku0fpw7yWVLdu2X6h0H7zScfYAXal+bd/Z45nCpLZcMX8sdFZig2KaiNYTwNPq1xCmEQJGkQ3FcRIK+dtCltulyMIdalP0VgxZJusqne6zAhiaD8FxT2IhmpRoF4KGMH9sKtwliPAOvIP0K0FqF4AGif9hbhKJA8aQPkq3bLcEIOHblGh7H4rrFmhskmUIfoEdSCMd0NZJ4y3hJU8A+K+Z4vbSxkOa2XafWlkOTFlGfLLm+jZViIFKcA8b8Sn5ZjCXM04u9Pf96MISNaBNGWqMJld4BjnhGRFWndqOifBIrF1GgI="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "qU1A2BovTCOULvHDjKbj2QFFiy6nNXfxGSJQYMlmiuHeAX4Aj9QOYJmRUTXRH5YxSZx1zpY5nVlZ8IlV/r17CBnV8ADlJgY31jBK1uQt+L0ZlScCRw3u2jstsmOWtnhw5lAkG/xAezGGbUUAIfMPxBgajwLAnBYbcOB7kjtanrHvWPcCUegHMBRv81DufQLYHY4/ulT/d4ETqhPTRDxFGodDc2G9FvXXcOHllZP2WN0OJFA+n2qD+nwMIvFze80s3VBIfrHhL6IQEPt9OSYULjImcZW5mu03taxKbdZBUJnKw8tY2PFmxgGwZEDBqEys3lL/2sMMu48IPGI+icgjev3paP4iC4lGAyETiD1Db5T/UYkO4QnKuI1muHffaqj1hO88im7PohT0YP4j3Fbm4Q1xeiIFNHonRmkVxshlLmy+iX96kCSxO5qhr4Bfg28EEBHeumaGosjzkNtlYyk3sdIP6SeIxyfCslsV1LVh8eyuPcmED3/V1Jm8G7BOKA0dGL+1X1SQtWTrzZ+uQadhB3wV81apw4YBDaS1VxKn4KLqiE+j/rJf80pkaxfVI/24t3aAxGkBMLIrkrKvIpG7Zl1rLCYA18IDWrwujcgxZF1K3zMuJCluPeV+Zq2rAXsqX4XYKs9F3jQutoPGlhkA8lFWApKX98k5yKPuTfNSG8M="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "TW9kux2EHijuEmMLug4zamXdAgaVhOR++7MQuRUnoVP6aD5o5DwTA3OJGCe+36UdkZiS5+ZH87Vjyn1NHoK7zqENQh/A/n8p0U6ZI4S5G9rZiIyO5mcYX80kR0YAflmZT//8DHHR9a5qLn3OMc2Turm0Y4V1DSf43lToE7pjhQ46W9gZdAkpbYXoNWiFsGJ3YKR+9NISPxsCscgmm/poIwh7hIs6uswp94tUAynzVABgsuAuonXZWzGhgDRQ4kingvwTfq68mxZPR/rCqDrVSPOLQP6OqmlVJXRMpzBhZk6BFTVBoR1kbT2+iQHlKsiiIN1AmN+0B1mvDJ+a54fFKuVWm68DMvr0sDWZ9c35uIyZuR9xyQT5gulxQXF0ZAHGF7EHPIdXLk/zFsnwoGHO04tHIC2t/I0gEYD/77rP0z3bQ7N8kPeh75q1V5Udehezt5iE6xx73pFSoiB1ef64U7RTcvek8HUhuItqRUntWKqA+4SrhFIemVvYNijp1DPFQeQhH/JkenO2/2lKyR/0XftLrJYV/Up3MPOeUemdWlhRBdwaTTt52TUkn10S+wSK7xswpOFjcjs3eHP7810diS9+IqR7VeirVT9sAeopeiBttzjELAogRHkdWk2VIIu8djyqamoAz5sqtfc53DJuRw7zsgplfOAN0jCvNjLOPYg="
